apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tiyaskar2010/techverito_demo_backend:latest
        ports:
        - containerPort: 8080
        command: ["go"]
        args: ["run", "main.go"]
        env:
        - name: DB_HOST
          value: "65.0.169.250"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "employee"
        - name: DB_PORT
          value: "5432"
        - name: ALLOWED_ORIGINS
          value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30002