name: TechVerito-demo

on:
  push:
    branches: 
      - main

jobs:

  build-and-test-go-backend:
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.GIT_TOKEN }}
          
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    
    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: cd ./backend/ && go get ./...

    
    - name: 'Build and push ${{ github.head_ref }} Image'
      if: success()
      uses: docker/build-push-action@v4
      with:
        context: ./backend/
        file: ./backend/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: '${{ secrets.DOCKERHUB_USERNAME }}/techverito_demo:tagname'
    

