name: TechVerito-demo

on:
  push:
    branches: 
      - main

jobs:

  build-and-test-go-backend:
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.GIT_TOKEN }}
          
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build
      run: cd devops-fullstack-app/backend && go get ./...

    - name: Test
      run: cd devops-fullstack-app/backend && go test -v ./...
